// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace StoreRestoreTabs
{
    internal sealed partial class Vsix
    {
        public const string Id = "StoreRestoreTabs.cce6207b-d708-4445-b9ae-adf17c8fd2c7";
        public const string Name = "StoreRestoreTabs";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Tomáš Krchňák";
        public const string Tags = "";
    }
}
